### ISSUE TITLE
defaulty fill fields for width and height with 100

### ISSUE THREAD

**Issue by derpac** [alvierahman90/derpic#13]
when selecting a custom URL the fields for width and height should auto populate with 100 so the user can quick copy the Url without having to tedeiously fill in 100 and 100 into those fields perhaps even set rotation to 0 defaulty

**Comment by alvierahman90** [comment]
perhaps blank does just not append that info to the url? keeps url nice and short

**Comment by derpac** [comment]
if width, height or rotation are left blank and/or flipv/h checkboxes are off then they are not included in the url! The numbers are not auto filled into the boxes but will allow you to copy
